### ISSUE TITLE
problem to parse char '(' or ')' for string value

### ISSUE THREAD

**Issue by aa-dxp168** [fslev/json-compare#2]
### PROBLEM ###

Wherever char  '(' or ')' are in the string, the comparison stops working. It says,
```
"java.lang.RuntimeException: java.lang.AssertionError: Expected element from position 1 was NOT FOUND:
{...}
	at org.junit.Assert.fail(Assert.java:88)
	at ro.skyah.comparator.JSONCompare.assertEquals(JSONCompare.java:49)
	at ro.skyah.comparator.JSONCompare.assertEquals(JSONCompare.java:33)
	at ro.skyah.comparator.JSONCompare.assertEquals(JSONCompare.java:21)
	at com.arbormetrix.aqi.fhir.dstu3.mapper.TestingUtils.compareJsonStrings(TestingUtils.java:28)
	... 25 more
```

**Comment by fslev** [comment]
This is because '(' is a regex symbol. Use \\Q(\\E and tell me if it worked. Otherwise, provide a code snippet

**Comment by fslev** [comment]
I've made a test myself and it seems that it works:
```
    @Test
    public void testIssue() {
        String expected =
                "{\"field\":[\"value wi(th parentheses\", 4, 3]}";
        String actual =
                "{\"field\":[3, 4, \"value wi(th parentheses\"]}";
        JSONCompare.assertEquals(expected, actual);
    }
```
